// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/pb/protozpb/protozpb.proto

package protozpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A simple message for testing your protoz utility
type Dummy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dummy) Reset() {
	*x = Dummy{}
	mi := &file_internal_pb_protozpb_protozpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dummy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dummy) ProtoMessage() {}

func (x *Dummy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protozpb_protozpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dummy.ProtoReflect.Descriptor instead.
func (*Dummy) Descriptor() ([]byte, []int) {
	return file_internal_pb_protozpb_protozpb_proto_rawDescGZIP(), []int{0}
}

func (x *Dummy) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dummy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_pb_protozpb_protozpb_proto protoreflect.FileDescriptor

const file_internal_pb_protozpb_protozpb_proto_rawDesc = "" +
	"\n" +
	"#internal/pb/protozpb/protozpb.proto\x12\x15i6.platform.cryptzrsa\"+\n" +
	"\x05Dummy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB4Z2go.code.infinity6.ai/platform/internal/pb/protozpbb\x06proto3"

var (
	file_internal_pb_protozpb_protozpb_proto_rawDescOnce sync.Once
	file_internal_pb_protozpb_protozpb_proto_rawDescData []byte
)

func file_internal_pb_protozpb_protozpb_proto_rawDescGZIP() []byte {
	file_internal_pb_protozpb_protozpb_proto_rawDescOnce.Do(func() {
		file_internal_pb_protozpb_protozpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_protozpb_protozpb_proto_rawDesc), len(file_internal_pb_protozpb_protozpb_proto_rawDesc)))
	})
	return file_internal_pb_protozpb_protozpb_proto_rawDescData
}

var file_internal_pb_protozpb_protozpb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_protozpb_protozpb_proto_goTypes = []any{
	(*Dummy)(nil), // 0: i6.platform.cryptzrsa.Dummy
}
var file_internal_pb_protozpb_protozpb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_protozpb_protozpb_proto_init() }
func file_internal_pb_protozpb_protozpb_proto_init() {
	if File_internal_pb_protozpb_protozpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_protozpb_protozpb_proto_rawDesc), len(file_internal_pb_protozpb_protozpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protozpb_protozpb_proto_goTypes,
		DependencyIndexes: file_internal_pb_protozpb_protozpb_proto_depIdxs,
		MessageInfos:      file_internal_pb_protozpb_protozpb_proto_msgTypes,
	}.Build()
	File_internal_pb_protozpb_protozpb_proto = out.File
	file_internal_pb_protozpb_protozpb_proto_goTypes = nil
	file_internal_pb_protozpb_protozpb_proto_depIdxs = nil
}
