// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: internal/pb/cryptzmsgpb/cryptzrsamsgpb.proto

package cryptzmsgpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RSAMessageCiphered struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Signature      []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SrcKey         string                 `protobuf:"bytes,3,opt,name=src_key,json=srcKey,proto3" json:"src_key,omitempty"`
	DstKey         string                 `protobuf:"bytes,4,opt,name=dst_key,json=dstKey,proto3" json:"dst_key,omitempty"`
	CipheredSymKey []byte                 `protobuf:"bytes,5,opt,name=ciphered_sym_key,json=cipheredSymKey,proto3" json:"ciphered_sym_key,omitempty"`
	CipheredData   []byte                 `protobuf:"bytes,6,opt,name=ciphered_data,json=cipheredData,proto3" json:"ciphered_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RSAMessageCiphered) Reset() {
	*x = RSAMessageCiphered{}
	mi := &file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSAMessageCiphered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSAMessageCiphered) ProtoMessage() {}

func (x *RSAMessageCiphered) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSAMessageCiphered.ProtoReflect.Descriptor instead.
func (*RSAMessageCiphered) Descriptor() ([]byte, []int) {
	return file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescGZIP(), []int{0}
}

func (x *RSAMessageCiphered) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RSAMessageCiphered) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RSAMessageCiphered) GetSrcKey() string {
	if x != nil {
		return x.SrcKey
	}
	return ""
}

func (x *RSAMessageCiphered) GetDstKey() string {
	if x != nil {
		return x.DstKey
	}
	return ""
}

func (x *RSAMessageCiphered) GetCipheredSymKey() []byte {
	if x != nil {
		return x.CipheredSymKey
	}
	return nil
}

func (x *RSAMessageCiphered) GetCipheredData() []byte {
	if x != nil {
		return x.CipheredData
	}
	return nil
}

var File_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto protoreflect.FileDescriptor

const file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDesc = "" +
	"\n" +
	",internal/pb/cryptzmsgpb/cryptzrsamsgpb.proto\x12\x15i6.platform.cryptzmsg\"\xcd\x01\n" +
	"\x12RSAMessageCiphered\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x17\n" +
	"\asrc_key\x18\x03 \x01(\tR\x06srcKey\x12\x17\n" +
	"\adst_key\x18\x04 \x01(\tR\x06dstKey\x12(\n" +
	"\x10ciphered_sym_key\x18\x05 \x01(\fR\x0ecipheredSymKey\x12#\n" +
	"\rciphered_data\x18\x06 \x01(\fR\fcipheredDataB7Z5go.code.infinity6.ai/platform/internal/pb/cryptzmsgpbb\x06proto3"

var (
	file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescOnce sync.Once
	file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescData []byte
)

func file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescGZIP() []byte {
	file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescOnce.Do(func() {
		file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDesc), len(file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDesc)))
	})
	return file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDescData
}

var file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_goTypes = []any{
	(*RSAMessageCiphered)(nil), // 0: i6.platform.cryptzmsg.RSAMessageCiphered
}
var file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_init() }
func file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_init() {
	if File_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDesc), len(file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_goTypes,
		DependencyIndexes: file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_depIdxs,
		MessageInfos:      file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_msgTypes,
	}.Build()
	File_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto = out.File
	file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_goTypes = nil
	file_internal_pb_cryptzmsgpb_cryptzrsamsgpb_proto_depIdxs = nil
}
