// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.5
// source: internal/pb/cryptzjwtpb/cryptzjwtpb.proto

package cryptzjwtpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JWTHeader defines the structure of the JWT header.
type JWTHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alg           string                 `protobuf:"bytes,1,opt,name=alg,proto3" json:"alg,omitempty"`
	Typ           string                 `protobuf:"bytes,2,opt,name=typ,proto3" json:"typ,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTHeader) Reset() {
	*x = JWTHeader{}
	mi := &file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTHeader) ProtoMessage() {}

func (x *JWTHeader) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTHeader.ProtoReflect.Descriptor instead.
func (*JWTHeader) Descriptor() ([]byte, []int) {
	return file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescGZIP(), []int{0}
}

func (x *JWTHeader) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *JWTHeader) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *JWTHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// JWTPayload defines the claims within the JWT.
type JWTPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Iss           string                 `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`
	Sub           string                 `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty"`
	Iat           int64                  `protobuf:"varint,4,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Aud           string                 `protobuf:"bytes,6,opt,name=aud,proto3" json:"aud,omitempty"`
	Typ           string                 `protobuf:"bytes,7,opt,name=typ,proto3" json:"typ,omitempty"`
	Ext           string                 `protobuf:"bytes,8,opt,name=ext,proto3" json:"ext,omitempty"`
	Bxt           []byte                 `protobuf:"bytes,9,opt,name=bxt,proto3" json:"bxt,omitempty"`
	Idp           string                 `protobuf:"bytes,10,opt,name=idp,proto3" json:"idp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTPayload) Reset() {
	*x = JWTPayload{}
	mi := &file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTPayload) ProtoMessage() {}

func (x *JWTPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTPayload.ProtoReflect.Descriptor instead.
func (*JWTPayload) Descriptor() ([]byte, []int) {
	return file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescGZIP(), []int{1}
}

func (x *JWTPayload) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *JWTPayload) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *JWTPayload) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *JWTPayload) GetIat() int64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *JWTPayload) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *JWTPayload) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *JWTPayload) GetTyp() string {
	if x != nil {
		return x.Typ
	}
	return ""
}

func (x *JWTPayload) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *JWTPayload) GetBxt() []byte {
	if x != nil {
		return x.Bxt
	}
	return nil
}

func (x *JWTPayload) GetIdp() string {
	if x != nil {
		return x.Idp
	}
	return ""
}

// JWTToken represents the full signed token structure.
type JWTToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *JWTHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload       *JWTPayload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTToken) Reset() {
	*x = JWTToken{}
	mi := &file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTToken) ProtoMessage() {}

func (x *JWTToken) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTToken.ProtoReflect.Descriptor instead.
func (*JWTToken) Descriptor() ([]byte, []int) {
	return file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescGZIP(), []int{2}
}

func (x *JWTToken) GetHeader() *JWTHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *JWTToken) GetPayload() *JWTPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_pb_cryptzjwtpb_cryptzjwtpb_proto protoreflect.FileDescriptor

const file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDesc = "" +
	"\n" +
	")internal/pb/cryptzjwtpb/cryptzjwtpb.proto\x12\x13i6.cryptz.cryptzjwt\"A\n" +
	"\tJWTHeader\x12\x10\n" +
	"\x03alg\x18\x01 \x01(\tR\x03alg\x12\x10\n" +
	"\x03typ\x18\x02 \x01(\tR\x03typ\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"\xc0\x01\n" +
	"\n" +
	"JWTPayload\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x10\n" +
	"\x03iss\x18\x02 \x01(\tR\x03iss\x12\x10\n" +
	"\x03sub\x18\x03 \x01(\tR\x03sub\x12\x10\n" +
	"\x03iat\x18\x04 \x01(\x03R\x03iat\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03aud\x18\x06 \x01(\tR\x03aud\x12\x10\n" +
	"\x03typ\x18\a \x01(\tR\x03typ\x12\x10\n" +
	"\x03ext\x18\b \x01(\tR\x03ext\x12\x10\n" +
	"\x03bxt\x18\t \x01(\fR\x03bxt\x12\x10\n" +
	"\x03idp\x18\n" +
	" \x01(\tR\x03idp\"}\n" +
	"\bJWTToken\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.i6.cryptz.cryptzjwt.JWTHeaderR\x06header\x129\n" +
	"\apayload\x18\x02 \x01(\v2\x1f.i6.cryptz.cryptzjwt.JWTPayloadR\apayloadB<Z:github.com/infinity6-ai/gox/cryptz/internal/pb/cryptzjwtpbb\x06proto3"

var (
	file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescOnce sync.Once
	file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescData []byte
)

func file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescGZIP() []byte {
	file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescOnce.Do(func() {
		file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDesc), len(file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDesc)))
	})
	return file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDescData
}

var file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_goTypes = []any{
	(*JWTHeader)(nil),  // 0: i6.cryptz.cryptzjwt.JWTHeader
	(*JWTPayload)(nil), // 1: i6.cryptz.cryptzjwt.JWTPayload
	(*JWTToken)(nil),   // 2: i6.cryptz.cryptzjwt.JWTToken
}
var file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_depIdxs = []int32{
	0, // 0: i6.cryptz.cryptzjwt.JWTToken.header:type_name -> i6.cryptz.cryptzjwt.JWTHeader
	1, // 1: i6.cryptz.cryptzjwt.JWTToken.payload:type_name -> i6.cryptz.cryptzjwt.JWTPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_init() }
func file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_init() {
	if File_internal_pb_cryptzjwtpb_cryptzjwtpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDesc), len(file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_goTypes,
		DependencyIndexes: file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_depIdxs,
		MessageInfos:      file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_msgTypes,
	}.Build()
	File_internal_pb_cryptzjwtpb_cryptzjwtpb_proto = out.File
	file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_goTypes = nil
	file_internal_pb_cryptzjwtpb_cryptzjwtpb_proto_depIdxs = nil
}
